// ─────────────────────────────────────────────────────────────────────────────
// GENERATED FILE — do not edit.
//
// Mirror of chum-inv-backend/src/config/access.ts, produced by
//     cd chum-inv-backend && node scripts/gen-frontend-access.js
//
// THIS COPY DECIDES WHAT IS SHOWN. The backend copy decides what is ALLOWED,
// and re-checks every code server-side, so hiding something here is UX rather
// than a control. When the two drift, the symptom is a button that appears and
// then 403s — which reads to the user as a broken application rather than as a
// missing permission. Hence the generator.
// ─────────────────────────────────────────────────────────────────────────────

export const ACCESS = {
  DASHBOARD_VOIR: "dashboard.voir",
  ARTICLES_VOIR: "articles.voir",
  ARTICLES_VOIR_TOUS_SERVICES: "articles.voir_tous_services",
  ARTICLES_CREER: "articles.creer",
  ARTICLES_CREER_GROUPE: "articles.creer_groupe",
  ARTICLES_CREER_REGISTRE: "articles.creer_registre",
  ARTICLES_MODIFIER: "articles.modifier",
  ARTICLES_SUPPRIMER: "articles.supprimer",
  ARTICLES_VOIR_SUPPRIMES: "articles.voir_supprimes",
  ARTICLES_RESTAURER: "articles.restaurer",
  ARTICLES_HISTORIQUE: "articles.historique",
  ARTICLES_PRESENCE: "articles.presence",
  ARTICLES_ETIQUETTE: "articles.etiquette",
  ARTICLES_FICHE: "articles.fiche",
  MOUVEMENTS_VOIR: "mouvements.voir",
  REFORME_PROPOSER: "mouvements.reforme.proposer",
  REFORME_DIRECTE: "mouvements.reforme.directe",
  REFORME_VOIR: "mouvements.reforme.voir",
  REFORME_PV_CREER: "mouvements.reforme.pv_creer",
  REFORME_PV_VALIDER: "mouvements.reforme.pv_valider",
  REFORME_PV_IMPRIMER: "mouvements.reforme.pv_imprimer",
  TRANSFERT_INTERNE: "mouvements.transfert.interne",
  TRANSFERT_EXTERNE: "mouvements.transfert.externe",
  TRANSFERT_DEMANDER: "mouvements.transfert.demander",
  TRANSFERT_VOIR: "mouvements.transfert.voir",
  TRANSFERT_FICHE_CREER: "mouvements.transfert.fiche_creer",
  TRANSFERT_FICHE_VALIDER: "mouvements.transfert.fiche_valider",
  TRANSFERT_FICHE_IMPRIMER: "mouvements.transfert.fiche_imprimer",
  INTERVENTIONS_VOIR: "interventions.voir",
  INTERVENTIONS_VOIR_TOUS_SERVICES: "interventions.voir_tous_services",
  INTERVENTIONS_DECLARER: "interventions.declarer",
  INTERVENTIONS_PRENDRE_EN_CHARGE: "interventions.prendre_en_charge",
  INTERVENTIONS_PLANIFIER: "interventions.planifier",
  INTERVENTIONS_RAPPORT: "interventions.rapport",
  INTERVENTIONS_CLOTURER: "interventions.cloturer",
  INTERVENTIONS_ANNULER: "interventions.annuler",
  INTERVENTIONS_FACTURER: "interventions.facturer",
  INTERVENTIONS_AGENDA: "interventions.agenda",
  INTERVENTIONS_IMPRIMER: "interventions.imprimer",
  IMPRESSION_VOIR: "impression.voir",
  IMPRESSION_INVENTAIRE_LOCALISATION: "impression.inventaire_localisation",
  IMPRESSION_INVENTAIRE_SERVICE: "impression.inventaire_service",
  IMPRESSION_ETIQUETTES_LOT: "impression.etiquettes_lot",
  STATISTIQUES_VOIR: "statistiques.voir",
  STATISTIQUES_VALORISATION: "statistiques.valorisation",
  RAPPORTS_VOIR: "rapports.voir",
  RAPPORTS_LOCALISATION: "rapports.localisation",
  RAPPORTS_CARNET: "rapports.carnet",
  RAPPORTS_PAR_CATEGORIE: "rapports.par_categorie",
  RAPPORTS_MOUVEMENTS: "rapports.mouvements",
  RAPPORTS_INTERVENTIONS: "rapports.interventions",
  RAPPORTS_VALORISATION: "rapports.valorisation",
  RAPPORTS_EXPORT_EXCEL: "rapports.export_excel",
  PERSONNEL_VOIR: "personnel.voir",
  PERSONNEL_MESSAGERIE: "personnel.messagerie",
  CONFIG_VOIR: "config.voir",
  CONFIG_ANNUAIRE_VOIR: "config.annuaire.voir",
  CONFIG_CATALOGUE_VOIR: "config.catalogue.voir",
  CONFIG_CATALOGUE_CREER: "config.catalogue.creer",
  CONFIG_CATALOGUE_MODIFIER: "config.catalogue.modifier",
  CONFIG_CATALOGUE_SUPPRIMER: "config.catalogue.supprimer",
  CONFIG_STRUCTURE_VOIR: "config.structure.voir",
  CONFIG_STRUCTURE_CREER: "config.structure.creer",
  CONFIG_STRUCTURE_MODIFIER: "config.structure.modifier",
  CONFIG_STRUCTURE_RETIRER: "config.structure.retirer",
  CONFIG_TIERS_VOIR: "config.tiers.voir",
  CONFIG_TIERS_CREER: "config.tiers.creer",
  CONFIG_TIERS_MODIFIER: "config.tiers.modifier",
  CONFIG_TIERS_SUPPRIMER: "config.tiers.supprimer",
  CONFIG_COMPTES_VOIR: "config.comptes.voir",
  CONFIG_COMPTES_CREER: "config.comptes.creer",
  CONFIG_COMPTES_MODIFIER: "config.comptes.modifier",
  CONFIG_COMPTES_RESET_PASSWORD: "config.comptes.reset_password",
  CONFIG_COMPTES_ACTIVER: "config.comptes.activer",
  CONFIG_ROLES_VOIR: "config.roles.voir",
  CONFIG_ROLES_CREER: "config.roles.creer",
  CONFIG_ROLES_MODIFIER: "config.roles.modifier",
  CONFIG_ROLES_ACCES: "config.roles.acces",
  CONFIG_GENERAL_VOIR: "config.general.voir",
  CONFIG_GENERAL_MODIFIER: "config.general.modifier",
  ADMIN_VOIR: "admin.voir",
  ADMIN_COMPTES_SYSTEME_VOIR: "admin.comptes_systeme.voir",
  ADMIN_COMPTES_SYSTEME_CREER: "admin.comptes_systeme.creer",
  ADMIN_COMPTES_SYSTEME_MODIFIER: "admin.comptes_systeme.modifier",
  ADMIN_COMPTES_SYSTEME_RESET_PASSWORD: "admin.comptes_systeme.reset_password",
  ADMIN_COMPTES_SYSTEME_ACTIVER: "admin.comptes_systeme.activer",
  ADMIN_SERVICES_VOIR: "admin.services.voir",
  ADMIN_ROLES_VOIR: "admin.roles.voir",
  ADMIN_ROLES_CREER: "admin.roles.creer",
  ADMIN_ROLES_MODIFIER: "admin.roles.modifier",
  ADMIN_ROLES_ACCES: "admin.roles.acces",
  ADMIN_MIGRATION_VOIR: "admin.migration.voir",
  ADMIN_MIGRATION_EXECUTER: "admin.migration.executer",
  COMPTE_CHANGER_CONTEXTE: "compte.changer_contexte",
} as const;

export type AccessCode = (typeof ACCESS)[keyof typeof ACCESS];

export const ACCESS_MODULES = ["dashboard","articles","mouvements","interventions","impression","statistiques","rapports","personnel","config","admin","compte"] as const;

export type AccessModule = (typeof ACCESS_MODULES)[number];

export const ACCESS_MODULE_LABELS: Record<AccessModule, string> = {
  "dashboard": "Tableau de bord",
  "articles": "Articles",
  "mouvements": "Réforme & transfert",
  "interventions": "Interventions",
  "impression": "Impressions",
  "statistiques": "Statistiques",
  "rapports": "Rapports",
  "personnel": "Personnel",
  "config": "Configuration",
  "admin": "Administration",
  "compte": "Mon compte",
};

export interface AccessDef {
  libelle: string;
  module: AccessModule;
  type: "page" | "action";
  ordre: number;
}

export const ACCESS_META: Record<AccessCode, AccessDef> = {
  "dashboard.voir": { libelle: "Accéder au tableau de bord", module: "dashboard", type: "page", ordre: 1 },
  "articles.voir": { libelle: "Consulter les articles", module: "articles", type: "page", ordre: 1 },
  "articles.voir_tous_services": { libelle: "Consulter les articles de tous les services", module: "articles", type: "action", ordre: 2 },
  "articles.creer": { libelle: "Créer un article", module: "articles", type: "action", ordre: 3 },
  "articles.creer_groupe": { libelle: "Créer un groupe d'articles", module: "articles", type: "action", ordre: 4 },
  "articles.creer_registre": { libelle: "Créer un article du registre (numéro saisi)", module: "articles", type: "action", ordre: 4.5 },
  "articles.modifier": { libelle: "Modifier un article", module: "articles", type: "action", ordre: 5 },
  "articles.supprimer": { libelle: "Supprimer un article", module: "articles", type: "action", ordre: 6 },
  "articles.voir_supprimes": { libelle: "Consulter les articles supprimés", module: "articles", type: "page", ordre: 7 },
  "articles.restaurer": { libelle: "Restaurer un article supprimé", module: "articles", type: "action", ordre: 8 },
  "articles.historique": { libelle: "Consulter l'historique d'un article", module: "articles", type: "action", ordre: 9 },
  "articles.presence": { libelle: "Confirmer la présence physique d'un article", module: "articles", type: "action", ordre: 10 },
  "articles.etiquette": { libelle: "Imprimer l'étiquette (code-barres / QR)", module: "articles", type: "action", ordre: 11 },
  "articles.fiche": { libelle: "Imprimer la fiche d'un article", module: "articles", type: "action", ordre: 12 },
  "mouvements.voir": { libelle: "Consulter les mouvements", module: "mouvements", type: "page", ordre: 1 },
  "mouvements.reforme.proposer": { libelle: "Proposer un article à la réforme", module: "mouvements", type: "action", ordre: 11 },
  "mouvements.reforme.directe": { libelle: "Réformer directement (sans demande)", module: "mouvements", type: "action", ordre: 12 },
  "mouvements.reforme.voir": { libelle: "Consulter les réformes et leurs PV", module: "mouvements", type: "page", ordre: 10 },
  "mouvements.reforme.pv_creer": { libelle: "Créer un PV de réforme", module: "mouvements", type: "action", ordre: 12 },
  "mouvements.reforme.pv_valider": { libelle: "Valider un PV de réforme", module: "mouvements", type: "action", ordre: 13 },
  "mouvements.reforme.pv_imprimer": { libelle: "Imprimer un PV de réforme", module: "mouvements", type: "action", ordre: 14 },
  "mouvements.transfert.interne": { libelle: "Transférer dans son propre service", module: "mouvements", type: "action", ordre: 20 },
  "mouvements.transfert.externe": { libelle: "Transférer vers un autre service", module: "mouvements", type: "action", ordre: 21 },
  "mouvements.transfert.demander": { libelle: "Demander le transfert d'un article", module: "mouvements", type: "action", ordre: 21 },
  "mouvements.transfert.voir": { libelle: "Consulter les transferts et leurs fiches", module: "mouvements", type: "page", ordre: 20 },
  "mouvements.transfert.fiche_creer": { libelle: "Créer une fiche de transfert", module: "mouvements", type: "action", ordre: 22 },
  "mouvements.transfert.fiche_valider": { libelle: "Valider une fiche de transfert", module: "mouvements", type: "action", ordre: 23 },
  "mouvements.transfert.fiche_imprimer": { libelle: "Imprimer une fiche de transfert", module: "mouvements", type: "action", ordre: 24 },
  "interventions.voir": { libelle: "Consulter les interventions", module: "interventions", type: "page", ordre: 1 },
  "interventions.voir_tous_services": { libelle: "Consulter les interventions de tous les services", module: "interventions", type: "action", ordre: 2 },
  "interventions.declarer": { libelle: "Déclarer une intervention", module: "interventions", type: "action", ordre: 3 },
  "interventions.prendre_en_charge": { libelle: "Prendre en charge une intervention", module: "interventions", type: "action", ordre: 4 },
  "interventions.planifier": { libelle: "Planifier et affecter une intervention", module: "interventions", type: "action", ordre: 5 },
  "interventions.rapport": { libelle: "Rédiger le rapport d'intervention", module: "interventions", type: "action", ordre: 6 },
  "interventions.cloturer": { libelle: "Clôturer une intervention", module: "interventions", type: "action", ordre: 7 },
  "interventions.annuler": { libelle: "Annuler une intervention", module: "interventions", type: "action", ordre: 8 },
  "interventions.facturer": { libelle: "Saisir la facture d'une intervention", module: "interventions", type: "action", ordre: 9 },
  "interventions.agenda": { libelle: "Consulter l'agenda des interventions", module: "interventions", type: "page", ordre: 10 },
  "interventions.imprimer": { libelle: "Imprimer une fiche d'intervention", module: "interventions", type: "action", ordre: 11 },
  "impression.voir": { libelle: "Accéder aux impressions", module: "impression", type: "page", ordre: 1 },
  "impression.inventaire_localisation": { libelle: "Imprimer l'inventaire d'une localisation", module: "impression", type: "action", ordre: 2 },
  "impression.inventaire_service": { libelle: "Imprimer l'inventaire d'un service entier", module: "impression", type: "action", ordre: 3 },
  "impression.etiquettes_lot": { libelle: "Imprimer une planche d'étiquettes QR", module: "impression", type: "action", ordre: 4 },
  "statistiques.voir": { libelle: "Accéder aux statistiques", module: "statistiques", type: "page", ordre: 1 },
  "statistiques.valorisation": { libelle: "Voir les montants dans les statistiques", module: "statistiques", type: "action", ordre: 2 },
  "rapports.voir": { libelle: "Accéder aux rapports et statistiques", module: "rapports", type: "page", ordre: 1 },
  "rapports.localisation": { libelle: "Rapport de localisation", module: "rapports", type: "page", ordre: 2 },
  "rapports.carnet": { libelle: "Carnet d'inventaire", module: "rapports", type: "page", ordre: 3 },
  "rapports.par_categorie": { libelle: "Rapports par catégorie", module: "rapports", type: "page", ordre: 4 },
  "rapports.mouvements": { libelle: "Rapport des mouvements", module: "rapports", type: "page", ordre: 5 },
  "rapports.interventions": { libelle: "Rapport des interventions", module: "rapports", type: "page", ordre: 6 },
  "rapports.valorisation": { libelle: "Consulter la valorisation du patrimoine", module: "rapports", type: "page", ordre: 7 },
  "rapports.export_excel": { libelle: "Exporter vers Excel", module: "rapports", type: "action", ordre: 8 },
  "personnel.voir": { libelle: "Consulter le personnel connecté", module: "personnel", type: "page", ordre: 1 },
  "personnel.messagerie": { libelle: "Utiliser la messagerie", module: "personnel", type: "action", ordre: 2 },
  "config.voir": { libelle: "Accéder à la configuration", module: "config", type: "page", ordre: 1 },
  "config.annuaire.voir": { libelle: "Consulter l'annuaire du personnel", module: "config", type: "page", ordre: 2 },
  "config.catalogue.voir": { libelle: "Consulter le catalogue (catégories, familles, sous-familles)", module: "config", type: "page", ordre: 10 },
  "config.catalogue.creer": { libelle: "Créer une entrée de catalogue", module: "config", type: "action", ordre: 11 },
  "config.catalogue.modifier": { libelle: "Modifier une entrée de catalogue", module: "config", type: "action", ordre: 12 },
  "config.catalogue.supprimer": { libelle: "Supprimer une entrée de catalogue", module: "config", type: "action", ordre: 13 },
  "config.structure.voir": { libelle: "Consulter les localisations", module: "config", type: "page", ordre: 20 },
  "config.structure.creer": { libelle: "Créer une localisation", module: "config", type: "action", ordre: 21 },
  "config.structure.modifier": { libelle: "Modifier une localisation", module: "config", type: "action", ordre: 22 },
  "config.structure.retirer": { libelle: "Retirer / réactiver une localisation", module: "config", type: "action", ordre: 23 },
  "config.tiers.voir": { libelle: "Consulter les tiers (fournisseurs, fabricants, techniciens)", module: "config", type: "page", ordre: 30 },
  "config.tiers.creer": { libelle: "Créer un tiers", module: "config", type: "action", ordre: 31 },
  "config.tiers.modifier": { libelle: "Modifier un tiers", module: "config", type: "action", ordre: 32 },
  "config.tiers.supprimer": { libelle: "Désactiver un tiers", module: "config", type: "action", ordre: 33 },
  "config.comptes.voir": { libelle: "Consulter les comptes", module: "config", type: "page", ordre: 40 },
  "config.comptes.creer": { libelle: "Créer un compte", module: "config", type: "action", ordre: 41 },
  "config.comptes.modifier": { libelle: "Modifier un compte", module: "config", type: "action", ordre: 42 },
  "config.comptes.reset_password": { libelle: "Réinitialiser un mot de passe", module: "config", type: "action", ordre: 43 },
  "config.comptes.activer": { libelle: "Activer / désactiver un compte", module: "config", type: "action", ordre: 44 },
  "config.roles.voir": { libelle: "Consulter les rôles", module: "config", type: "page", ordre: 50 },
  "config.roles.creer": { libelle: "Créer un rôle", module: "config", type: "action", ordre: 51 },
  "config.roles.modifier": { libelle: "Modifier un rôle", module: "config", type: "action", ordre: 52 },
  "config.roles.acces": { libelle: "Modifier les accès d'un rôle", module: "config", type: "action", ordre: 53 },
  "config.general.voir": { libelle: "Consulter les paramètres généraux", module: "config", type: "page", ordre: 60 },
  "config.general.modifier": { libelle: "Modifier les paramètres généraux (année d'inventaire, en-têtes)", module: "config", type: "action", ordre: 61 },
  "admin.voir": { libelle: "Accéder à l'administration", module: "admin", type: "page", ordre: 1 },
  "admin.comptes_systeme.voir": { libelle: "Consulter les comptes système", module: "admin", type: "page", ordre: 10 },
  "admin.comptes_systeme.creer": { libelle: "Créer un compte système", module: "admin", type: "action", ordre: 11 },
  "admin.comptes_systeme.modifier": { libelle: "Modifier un compte système", module: "admin", type: "action", ordre: 12 },
  "admin.comptes_systeme.reset_password": { libelle: "Réinitialiser le mot de passe d'un compte système", module: "admin", type: "action", ordre: 13 },
  "admin.comptes_systeme.activer": { libelle: "Activer / désactiver un compte système", module: "admin", type: "action", ordre: 14 },
  "admin.services.voir": { libelle: "Consulter tous les services", module: "admin", type: "page", ordre: 20 },
  "admin.roles.voir": { libelle: "Consulter tous les rôles", module: "admin", type: "page", ordre: 30 },
  "admin.roles.creer": { libelle: "Créer un rôle (toute portée)", module: "admin", type: "action", ordre: 31 },
  "admin.roles.modifier": { libelle: "Modifier n'importe quel rôle", module: "admin", type: "action", ordre: 32 },
  "admin.roles.acces": { libelle: "Modifier les accès de n'importe quel rôle", module: "admin", type: "action", ordre: 33 },
  "admin.migration.voir": { libelle: "Consulter l'état de la migration des données", module: "admin", type: "page", ordre: 40 },
  "admin.migration.executer": { libelle: "Exécuter une étape de migration", module: "admin", type: "action", ordre: 41 },
  "compte.changer_contexte": { libelle: "Changer de service / de contexte", module: "compte", type: "action", ordre: 1 },
};

export const ALL_ACCESS_CODES: AccessCode[] = Object.values(ACCESS);

/** True when `code` is a code this build knows about. */
export function isKnownAccessCode(code: string): code is AccessCode {
  return Object.prototype.hasOwnProperty.call(ACCESS_META, code);
}
